<a href="https://colab.research.google.com/github/Builesss/Arreglos_12_08_2025/blob/main/Vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Los vectores son una reserva de memoria para almacenar informacion, solo puede ser de un tipo, si es numerico, es numerico, si es texto, debe continuar siendo texto, esto aplica para las matrices.

Los arreglos son identificadores estaticos, esto significa que es otra forma de definir, varibales y constantes.

In [1]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
print(vector)

print(vector[2])

""" Los vectores no son como las listas, no tienen un metodo end() para agregar elementos
o tienen un metodo pop() para eliminar elemntos. pero si tienen metodo reshape() para cambiar
su forma, adicionalmente despues de creado no se puede cambiar el tamaño del vector."""

vector1 = np.zeros(5)
print(vector1)

vector2 = np.ones(5)
print(vector2)

vector3 = np.arange(1, 10)
print("rango", vector3)

vector4 = np.linspace(1, 10, 5)
print("linspace", vector4)

vector5 = np.random.rand(10)
print("random", vector5)

vector6 = np.random.randint(1, 10, 10)
print("random int", vector6)

[1 2 3 4 5]
3
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
rango [1 2 3 4 5 6 7 8 9]
linspace [ 1.    3.25  5.5   7.75 10.  ]
random [0.72169376 0.8021944  0.67568505 0.80374839 0.25830771 0.21067878
 0.09338536 0.87021108 0.04148779 0.50395494]
random int [9 1 1 9 1 1 8 9 7 7]
